### ISSUE TITLE
No Module Found

### ISSUE THREAD

**Issue by KDharmarajanDev** [BerkeleyAutomation/fogros2-rt-x#8]
In a Docker container with ROS 2 Humble, attempting to colcon build the repo results in the following error:

```
Failed to load entry point 'fgr': No module named 'fogros2_rt_x.exporter'
Traceback (most recent call last):
  File "/opt/ros/humble/bin/ros2", line 33, in <module>
    sys.exit(load_entry_point('ros2cli==0.18.8', 'console_scripts', 'ros2')())
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2cli/cli.py", line 52, in main
    add_subparsers_on_demand(
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2cli/command/__init__.py", line 237, in add_subparsers_on_demand
    extension = command_extensions[name]
KeyError: 'fgr'
```

**Comment by KeplerC** [comment]
Hi @KDharmarajanDev , I just fixed (1 minutes ago...) with commit 9627569f9b8a49f375be5b222e5f4c06edcd6a2c. See if the updated main works

**Comment by KDharmarajanDev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Colcon build entrypoint not found error](https://trello.com/c/SKpV25lB/12-colcon-build-entrypoint-not-found-error)

**Comment by KDharmarajanDev** [comment]
Build is successful on my end.
